FROM ubuntu
RUN apt-get update
RUN apt-get install maven openjdk-8-jdk -y
WORKDIR /src
COPY pom.xml .
COPY src src
RUN mvn verify

FROM openjdk:8-alpine
COPY --from=0 /src/target ./target
CMD cd target ; exec java -Xmx8m -Xms8m -jar words.jar
