FROM ubuntu
RUN apt-get update
RUN ["apt-get", "install", "figlet"]
#CMD figlet -f script hello
ENTRYPOINT ["figlet", "-f", "script"]
#if you don't use this syntax it executes /bin/sh => it prints it as well.
CMD ["Hello World"]
